### ISSUE TITLE
dra.

### ISSUE THREAD

**Issue by jfhartzell** [christiansteinert/tibetan-dictionary#41]
under listing for ལེ་, there is "Negi (Tibetan-Sanskrit) | dra.— ཐིག་ལེ། ས་ལེ་སྦྲམ། སོག་ལེ། ནེའུ་ལེ། ན་ལེ་ཤམ། ཕྱ་ལེ་བ།་"
"dra." is not hyperlinked, so it's not clear what the abbreviation refers to.

**Comment by christiansteinert** [comment]
With the recent fix that I made this should be working. You may have to clear your browser cache to see the change but with the latest change the term is underlined and the abbreviation is shown when hovering over it with a mouse...

![grafik](https://github.com/user-attachments/assets/fe99cd51-8a3e-4326-b605-60a07a4983cc)

**Comment by jfhartzell** [comment]
For the particular instance mentioned clearing browser of cookies didn't change anything. I also tried in a fresh browser and the issue remained. Perhaps it's just one instance that was missed?

**Comment by jfhartzell** [comment]
sorry, i tried again just now in Chrome and you're correct.

**Comment by christiansteinert** [comment]
Happy to hear that it works now as expected. If you continue to have problems, even if it is only with a particular browser, please do let me know. Many thanks!
